# Generated by Django 4.2.27 on 2026-02-02 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the uploaded file', max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_equipment', models.IntegerField(default=0)),
                ('avg_flowrate', models.FloatField(default=0.0)),
                ('avg_pressure', models.FloatField(default=0.0)),
                ('avg_temperature', models.FloatField(default=0.0)),
                ('type_distribution', models.TextField(default='{}', help_text='JSON string of equipment type distribution')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Equipment name', max_length=255)),
                ('equipment_type', models.CharField(help_text='Type of equipment', max_length=100)),
                ('flowrate', models.FloatField(help_text='Flowrate value')),
                ('pressure', models.FloatField(help_text='Pressure value')),
                ('temperature', models.FloatField(help_text='Temperature value')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.dataset')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
