# Generated by Django 4.2.28 on 2026-02-05 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for OTP verification', max_length=254)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('otp_type', models.CharField(choices=[('signup', 'Signup Verification'), ('password_reset', 'Password Reset')], help_text='Type of OTP (signup or password_reset)', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration timestamp')),
                ('is_used', models.BooleanField(default=False, help_text='Whether OTP has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user (null for signup OTPs before user is activated)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email OTP',
                'verbose_name_plural': 'Email OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'otp_type', 'is_used'], name='api_emailot_email_d8b80f_idx'), models.Index(fields=['expires_at'], name='api_emailot_expires_037b79_idx')],
            },
        ),
    ]
